# Generated by Django 4.2.16 on 2024-10-18 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='status',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='author',
            index=models.Index(fields=['name'], name='myapp_autho_name_6e7d38_idx'),
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['title'], name='myapp_book_title_9d2a56_idx'),
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['price'], name='myapp_book_price_a04fa9_idx'),
        ),
    ]
